### ISSUE TITLE
Allow users to create a customized report and send it as a link to others

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#1]
Rebecca and Brendan said that this was the most important feature for the MVP.

**Comment by robhudson** [comment]
If all the report parameters are included in the query string arguments, that should solve this, correct? I believe this is what the original distribution viewer did.

**Comment by lonnen** [comment]
I think this needs some clarity. It's unclear what customization they're expecting -- chart option manipulation?

**Comment by openjck** [comment]
I think the customization possibilities are covered by [these issues](https://github.com/mozilla/distribution-viewer/issues?q=is%3Aissue+is%3Aopen+label%3Aoption) but I followed up with Rebecca and Brendan to be sure.

**Comment by openjck** [comment]
More info from Brendan. I'm remembering now that this is also what he said in London. Apologies for mixing up the definition of _report_ when opening this issue. (_Report = list of charts, not a single chart_)

> Hi John, comments on those options below, but the most important thing in
> terms of being able to share customized reports is actually the ability to
> change the set of distributions shown and send a link to that set of views.
> For example, I could send you some quick facts about crashes:
> https://metrics.mozilla.com/protected/bcolloran/distributionViewer/distributionViewer.html?metrics=crashesPerActiveDay,pctDaysWithCrashes,numDaysWithCrashes,crashesPerSessionSecond,crashesPerTick,totalCrashes,numCrashesOnActiveDays&pops=allRecs
> 
> or facts about client activity:
> https://metrics.mozilla.com/protected/bcolloran/distributionViewer/distributionViewer.html?metrics=pagesAtMostRecentDay,numDays,pctDaysActiveOfPossible,sessPerDay,timePerDay,ticksPerDay,allSessionLength,allSessionTicks,allSessionActivePct,numSessionStartsOnActiveDays&pops=allRecs
> 
> or just a single view about addon use:
> https://metrics.mozilla.com/protected/bcolloran/distributionViewer/distributionViewer.html?metrics=numAddons&pops=allRecs

**Comment by robhudson** [comment]
In a meeting this morning we discussed this feature further.

The customization will either be a separate page or an overlay and provide the user with a choice of population and list of metrics to choose. Upon submit, the page will re-render with the selected choices and the URL in the browser will update so as to easily be shared, with all options chosen as query parameters.

Basically what was said here (https://github.com/mozilla/distribution-viewer/issues/1#issuecomment-240291836) but with a slight different UI than in the original FHR viewer.
