### ISSUE TITLE
Option to change graph display type (bars, ECDF, PDF, etc.)

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#10]
This should be shown in something like a pop-up menu that appears when hovering over the graph.

**Comment by openjck** [comment]
Comment from Brendan:

> This was an experimental alphaish feature in my version; I never really got it
> working in a way that displays the data accurately or meaningfully, and in
> truth doing so is non-trivial. The PDF option should definitely not be
> available for anything other than categorical types, and it should be low
> priority

**Comment by spasovski** [comment]
As per bcolloran this feature is no longer being requested.
