### ISSUE TITLE
Replace Django admin form with Google auth login

### ISSUE THREAD

**Issue by robhudson** [mozilla/distribution-viewer#108]
Logging in using Google auth will allow the user to visit the admin if `is_staff` is `True` and the appropriate model permissions are set up. However, logging in via the admin confuses the front-end because the Google auth settings aren't available.

Replacing the Django admin login with the Google auth login will fix this and allow admin access w/o requiring a Django password. Let's do that.

/cc @washort

**Comment by openjck** [comment]
Fixed with #142
