### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#13]
For V0, we'll need some type of authentication system, whether it be LDAP or Google or something else. The current dashboard uses LDAP.

**Comment by spasovski** [comment]
I thought we decided (in the Monday meeting) that this wouldn't need to be under any auth. We can leave this open if we'd like further confirmation and maybe I misunderstood.

**Comment by RishabhJain2018** [comment]
@openjck Can we use django-allauth for the social as well as the normal authentication ?

**Comment by RishabhJain2018** [comment]
@openjck @spasovski @robhudson Can we use django-allauth for social and normal authentication?

**Comment by lonnen** [comment]
Hey @RishabhJain2018 -- we appreciate the assistance. Distribution viewer is an internal tool and won't have a publicly accessible component for several iterations. If you're interested in contributing I can help you find a project that is better set up for outside contribution.

**Comment by RishabhJain2018** [comment]
@lonnen Its alright. So, how can I proceed to solve this issue?

**Comment by lonnen** [comment]
If you can find me lonnen@irc.mozilla.org I'd be happy to chat with you about your skills and interests, and direct you to a project where you can have a larger impact

**Comment by RishabhJain2018** [comment]
@lonnen yeah sure. :+1:

**Comment by RishabhJain2018** [comment]
@lonnen which channel should I join?

**Comment by robhudson** [comment]
We hang out in #datatools

**Comment by lonnen** [comment]
Talking to @Osmose about how SHIELD does this and they let django handle auth with a static page. Something to consider for us.

**Comment by openjck** [comment]
Fixed by #86
