### ISSUE TITLE
Create Dockerized deployment

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/distribution-viewer#135]
Eventually Services Ops will manage the production instance of Distribution Viewer in their infrastructure, instead of Heroku where it lives for development. To ease this transition, we'll need to get a Docker set up working, adhering as much as possible to the Service Ops team's recommended [DockerFlow practices](https://github.com/mozilla-services/Dockerflow).

**Comment by robhudson** [comment]
Switching to CircleCI for future home of Docker container build step was done in 82a4562f.

**Comment by robhudson** [comment]
Local development in Docker has been merged.

The next 2 steps I would consider for this bug are:
1. Update tests to run in a docker container. This would involve the tests building the docker container, including the static assets, and running both the frontend and backend tests in the docker container.
2. Building off of (1) push the trimmed docker container to docker hub. From there a deploy script can take it and deploy it.
