### ISSUE TITLE
Need introductory/explanatory text

### ISSUE THREAD

**Issue by bcolloran** [mozilla/distribution-viewer#164]
we need some introductory text to help folks understand how this works and point them in the direction of help if it's needed (kind of like what's at the top of https://metrics.mozilla.com/protected/bcolloran/distributionViewer/distributionViewer.html ). Let's use the following text (links in brackets [[link|url ]])

"""
The following plots are lightly processed [[empirical cumulative distribution functions| http://en.wikipedia.org/wiki/Empirical_distribution_function ]] of a number of key measures from a 1% sample of Firefox clients. Data is updated {weekly? is that right?}.

For help reading CDFs, take a look [[here| http://ukclimateprojections.metoffice.gov.uk/22619 ]] and  [[here| http://docs.battlemesh.org/v8/ecdf.html ]]. The key thing to remember is that places where the curve is very steep represent parts of the x-axis with many observations.

If you have any questions about how to interpret these charts, where the data came from and how it was processed, or suggestions or requests, please send a Slack message or email to [[bcolloran@mozilla.com |  mailto:bcolloran@mozilla.com]].
"""

When we get around to adding distribution comparisons, we'll need to ad some text explaining how that works, something like;
"when a line is farther to the right than another, that means it has more observations with higher values. Also recall that if a CDF"

**Comment by openjck** [comment]
Maybe on an *About* page
