### ISSUE TITLE
Operating system chart seems misleading

### ISSUE THREAD

**Issue by jtg567** [mozilla/distribution-viewer#165]
https://moz-distribution-viewer.herokuapp.com/chart/3/

This graph would suggest the majority of installations >60% are on Linux - it's common wisdom that Windows users make up the majority of the audience.

Also, although there is a a distinct value between Linux and Windows there's no corresponding tick mark for the category.

**Comment by robhudson** [comment]
See bug #167. If you load the main page directly and then click into this chart's page the hover tooltips will appear making the chart more understandable.

**Comment by rafrombrc** [comment]
Closing this issue because the values are correct (inasmuch as the cross-sectional data set is correct) but other issues (#166, #167, #202) are making this hard to interpret. We'll work on resolving the other issues.
