### ISSUE TITLE
Update text label for "date skew"

### ISSUE THREAD

**Issue by bcolloran** [mozilla/distribution-viewer#168]
as we discovered the other day, this is text label is confusing :-)

Let's update the string from "Date skew is the number of days by which a client machine's clock is thought to differ from the correct time."

to:
"""
 "Date skew" is the average number of days by which the date stamp recorded in the pings sent by a client differ from the the date they are received on the server. That is, for each client, we look at all of the pings that the client has sent, and we find the average number of days by which the date recorded in that ping on the client differ from the date on which that ping is received on the server. For example, if a client has "date skew" value of 5.3, that means that on average the client's pings have a server reception time stamp 5.3 days after the date recorded in the ping on the client. This measure incorporates both the effects of ping latency and incorrect client clocks.
"""

this chart shows the distribution of those values across clients. So, for example,

https://moz-distribution-viewer.herokuapp.com/chart/10/

**Comment by openjck** [comment]
Done on production
