### ISSUE TITLE
Use a different layout for this chart and charts like it

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#190]
https://gauss.telemetry.mozilla.org/chart/27/?pop=channel:release,channel:beta,channel:nightly

It may be as simple as there being no data points to display for those populations. I just want to verify that.

In either case, we should display a message if a chart contains no data due to the configuration options. See #189 about that.

**Comment by openjck** [comment]
Yep, it's just a simple case of there being no data for this chart. We'll add a *No Data* message with #189.

**Comment by openjck** [comment]
Actually, it looks like there is data for this chart, but only one point per population.

**Comment by openjck** [comment]
In fact, this chart is technically correct, except that the hover descriptions are wrong.

**Comment by openjck** [comment]
Hm. Except for the fact that the hover descriptions are wrong, this chart is technically correct (for each population, 100% of users use that population) but the layout is pretty weird. I'm not sure how we would want to lay this out instead. I'll come back to this one.

**Comment by rafrombrc** [comment]
As you said, this is actually correct behavior, so I'm inclined to table this one unless it becomes a usability problem.
