### ISSUE TITLE
Allow users to more easily select populations

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#193]
Currently, the user can visit the configuration page to change the populations that are displayed. I talked with Rob Miller about making that even easier, for example having some type of multi-select widget above the legend. Davor has also suggested having a lighbox overlay, which I also think would work well.

One added benefit of this is that it would allow users to more easily change the populations that are shown on the chart detail page. (At the moment, the configuration page always returns the user to the homepage chart listing even if they came from a chart detail page.)

**Comment by openjck** [comment]
@rafrombrc Can you say more about the motivation behind this? For example, have you heard from users that they want to be able to quickly toggle populations on and off to compare the charts before and after more quickly?

The implementation side of this doesn't seem too hard, but I'm just trying to think of the best interface for it. Wondering if a lightbox would be too distracting.

**Comment by openjck** [comment]
Just thinking out loud. I'm planning to add a *Configuration* section between the header and the chart(s) with all of the configuration options that are relevant to that page. It'll have a maximum height with a scrollbar. It'll be hidden by default but will open upon click.

**Comment by rafrombrc** [comment]
I don't know whether or not we've had many users yet, but I've definitely heard from the one user that is me that I'd like the populations UI to be more visible. It's not so much about toggling them quickly as it is about exposing the functionality, making it as easy as possible for folks to see and interact with the feature set.

My preference would be to separate the population selection from the rest of the configuration. I imagine something like the 'assignees' or 'labels' UI right here on this github issue page. Immediately visible on the page (maybe above the graph list on the left-hand side?) is a list of the currently displayed populations (default is the 'all' population). Clicking on an icon of some sort would show you the set of populations to choose from, with the current selections marked as selected. It would also allow you to select and deselect from the available set. The page wouldn't update until you've marked yourself as finished in some way... I'm not sure if simply clicking elsewhere on the page would be sufficient, or if it makes more sense to add an explicit "i'm done selecting" button of some sort.

Thoughts?

**Comment by openjck** [comment]
Thanks for the input.

I ended up designing it like this:

![](https://cloud.githubusercontent.com/assets/933396/23573210/67d97f8c-0042-11e7-823d-bf341c1790a5.gif)

The only major difference is that, in the end, the "Configuration" section will be hidden by default but will appear after clicking a gear icon or similar.

**Comment by openjck** [comment]
That said, if we want to surface the configuration options even more we *can* make them visible by default.
