### ISSUE TITLE
Compare different distributions of a population (OS, channel, etc.)

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#2]

**Comment by robhudson** [comment]
I'll be working on the backend portion of this next week, but only for release channel at this point. So the front-end options will be to show all or pick a release channel.

Rob Miller suggested we simply draw the charts with one population to start with. Later we can draw multiple populations on a single chart like the original DV did.

**Comment by robhudson** [comment]
I'll be working on the front-end of this. Assigning to myself.

**Comment by openjck** [comment]
Rob and I talked about the UI for this on IRC.

To use the example of release channel, we could mimic Brendan's dashboard by showing three differently-colored lines in each chart (one for each channel: release, beta, and nightly) and show a single legend above each chart or chart listing. We could also update the /configure/ page to provide options for which distribution(s) should be shown.

**Comment by robhudson** [comment]
Backend update merged in 04226afca4928a9358abf1b63438975e1a0bd04b
