### ISSUE TITLE
Research data storage and data computation options

### ISSUE THREAD

**Issue by robhudson** [mozilla/distribution-viewer#20]
There will exist a data set on a.t.m.o that contains a data points per client of 1% sample rate that will drive the graphs in the distribution viewer.

How we read and process this data to emit the aggregated data set to the front-end needs to be determined. This issue is for researching and discussing of this.

**Comment by robhudson** [comment]
Some ideas I will investigate to start off with:
- Loading the data into postgresql and performing aggregation queries on the fly
- Using Presto to perform aggregation queries on the fly
- Pre-compute a set of aggregations for most common views, perform on the fly and slower aggregations for the rest.

**Comment by robhudson** [comment]
For v0 and until we need anything more, I'm heading towards the route of pre-computing the aggregations and storing only those values. This can be done in a spark job, likely weekly to match the cadence of the raw data source updates. The aggregated data set can be pushed directly into our Postgresql backend and queried via Django, then adding some light processing to it to feed it to the API.

**Comment by lonnen** [comment]
The bugzilla side of this that we are waiting on is: https://bugzilla.mozilla.org/show_bug.cgi?id=1286573

**Comment by robhudson** [comment]
I will close this now. We are implementing what was mentioned in the 3rd comment.
