### ISSUE TITLE
Don't 500 if no data

### ISSUE THREAD

**Issue by robhudson** [mozilla/distribution-viewer#49]

**Comment by robhudson** [comment]
Locally I saw no 500 with empty tables.

I set up Sentry to get more info on what was going on, the sentry report is here:
https://sentry.prod.mozaws.net/operations/distribution-viewer/issues/344708/

Turns out we never ran the database migrations. I ran the migrations and imported the sample data.

**Comment by openjck** [comment]
Does Heroku not run migrations automatically?

**Comment by robhudson** [comment]
> Does Heroku not run migrations automatically?

They do not. You have to run them manually via the `heroku run ...` commands.

**Comment by robhudson** [comment]
Looks like there is a way to automate it if we'd like to do that...
https://gist.github.com/kylefox/7044491259b6b2586ca1
