### ISSUE TITLE
Toggle for linear vs. logarithmic display

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#8]
Provide a toggle that controls whether the X value should be linear or logarithmic.

This should be shown in something like a pop-up menu that appears when hovering over the graph.

**Comment by openjck** [comment]
Comment from Brendan:

> Yep, we'll need [this option]. Remember that I'll also be providing a csv like
> the attached that includes default values for these options (as well as the
> data element description, the tooltip label, and a number of other
> configuration options)

I have the attachment archived with my mail.

**Comment by openjck** [comment]
The state management part of this is easy (it's the same as what we did with the _Show outliers_ feature) but until mozilla/metrics-graphics#712 is fixed logarithmic graphs won't be readable.

**Comment by openjck** [comment]
Note from Brendan:

> As an implementation detail, I advise using the asinh rather than the actual log function to implement the "log" scales -- this will avoid problems with undefined behavior for input values <=0. I have some js that worked with d3 v3 (attached), but it might not work with d3 v4, and I'm sure that I didn't do it correctly.

**Comment by openjck** [comment]
Depends on mozilla/metrics-graphics#712 or, in all likelihood, #87.

**Comment by openjck** [comment]
For this issue, let's use the standard D3 log scale. We can switch to an asinh scale with #151.

**Comment by spasovski** [comment]
Fully support this path.
