### ISSUE TITLE
use d3 directly for chart generation

### ISSUE THREAD

**Issue by spasovski** [mozilla/distribution-viewer#87]
Using an abstraction on top of D3 has been limiting with respect to fine-grained chart control. If we wish to reach a level of chart parity with Brendan's version we'd need to be better able to control curve smoothing and potentially hover states. React itself would also be better served by having the axes and path exposed so that we can re-render them on component updates rather than destroy and recreate the chart.

I had to do this earlier in order to diagnose a redux issue and it wasn't too involved (granted it didn't have all the features of MG).

**Comment by openjck** [comment]
Brendan mentioned some issues with the current charts in a recent email. We should address these while switching to D3:

> It looks like you're applying some kind of curve smoothing to the plots,
> probably some kind of interpolation (see screen cap pasted in below-- there are
> little squiggles around the discontinuities at which the plot should setp up
> (lmk if the cap doesn't come through, sometimes gmail eats pasted pics)). I
> assume you're using d3, in which case you should be able to use a step curve
> rather than an interpolating curve. See e.g. about 3/4 of the way down the page
> at: https://www.dashingd3js.com/svg-paths-and-d3js
> 
> The smoothing is even more pronounced an problematic for the cpu distribution:
> https://moz-distribution-viewer.herokuapp.com/chart/7/

**Comment by rafrombrc** [comment]
\o/
