### ISSUE TITLE
Return a 404 when a metric of a given ID (e.g. /chart/999/) can't be found

### ISSUE THREAD

**Issue by openjck** [mozilla/distribution-viewer#96]
### Steps to reproduce

Visit the chart detail page of a chart that doesn't exist (e.g. https://moz-distribution-viewer.herokuapp.com/chart/999/)
### Actual result

An error is printed to the console and the spinners spin indefinitely
### Expected result

404

**Comment by openjck** [comment]
@spasovski Do you know of a good way to do this using Redux? We dispatch the `GET_METRIC_FAILURE` action, but where would we catch and respond to it? I notice some other projects only dispatch `..._SUCCESS` actions and trigger 404s manually in `catch` blocks.

**Comment by robhudson** [comment]
I just checked.. the backend does return a 404. So this is a front-end dealio.

**Comment by openjck** [comment]
> I just checked.. the backend does return a 404. So this is a front-end dealio.

Yep, definitely. Sorry if I implied otherwise. The back-end is sending back a 404 as expected but we're not handling it on the front-end.

**Comment by spasovski** [comment]
@openjck it would be something similar to https://github.com/mozilla/shielddash/blob/master/shielddash/core/static/js/app/reducers/study-reducer.js#L40

The spinner would go away by the `isFetching` state and we'd render an error message instead.

**Comment by openjck** [comment]
> @openjck it would be something similar to https://github.com/mozilla/shielddash/blob/master/shielddash/core/static/js/app/reducers/study-reducer.js#L40
> 
> The spinner would go away by the isFetching state and we'd render an error message instead.

We dispatch an action like the one you linked to [here](https://github.com/mozilla/distribution-viewer/blob/master/distributionviewer/core/static/js/app/components/views/chart.js#L38). Where would we catch it?
